# Generated by Django 3.2.16 on 2025-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkdin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
