# Generated by Django 3.2.16 on 2025-06-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_linkdin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linkdin',
        ),
    ]
