# Generated by Django 3.2.16 on 2025-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_linkdin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
