# Generated by Django 3.2.16 on 2025-07-02 09:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', validators=[account.models.User.validate_jpg]),
        ),
    ]
