# Generated by Django 3.2.16 on 2025-07-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Image',
            new_name='image',
        ),
    ]
