# Generated by Django 3.2.16 on 2025-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_image_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
